routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'PostController@index')->name('posts');

Route::get('/mail', function() {
    $user = App\User::first();

    return new App\Mail\UserRegistered($user);
});

Route::get('/contact', 'ContactController@index')->name('contact.index');
Route::post('/contact', 'ContactController@send')->name('contact.send');
Route::get('/search', 'SearchController@index')->name('search');

//Route::get('/posts/{id}', 'PostController@show')->name('posts.show');

// instead of putting {id} in route signature
// we can put {post} in the route, so when we give 'posts/1' url to laravel, it will look for post of id: 1
//Route::get('/posts/{post}', 'PostController@show')->name('posts.show');

// we will retrieve posts with slug instead of post's id
Route::get('/posts/{slug}', 'PostController@show')->name('posts.show');
Route::get('/tag/{slug}', 'TagController@show')->name('tag.show');

Route::get('/about', function () {
    return view('pages.about');
})->name('about');

Route::get('/email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
Route::get('/email/resend', 'Auth\VerificationController@resend')->name('verification.resend');

Route::get('/account/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('/account/register', 'Auth\RegisterController@register');

Route::get('/account/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/account/login', 'Auth\LoginController@login');
Route::post('/account/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

Route::group(['prefix' => 'admin', 'middleware' => ['can:manage-posts', 'auth']], function() {
    Route::get('/post/create', 'Admin\PostController@create')->name('admin.post.create');
    Route::post('/post/create', 'Admin\PostController@store')->name('admin.post.store');
    Route::get('/post/{id}', 'Admin\PostController@edit')->name('admin.post.edit');
    Route::put('/post/{id}', 'Admin\PostController@update')->name('admin.post.update');
    Route::delete('/post/{id}', 'Admin\PostController@destroy')->name('admin.post.delete');
});

Route::post('/comment/create', 'CommentController@store')->name('comment.create');

Route::feeds();

app/Models/Post.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

use Spatie\Feed\Feedable;
use Spatie\Feed\FeedItem;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class Post extends Model implements Feedable
{
    protected $table = 'posts';

    protected $fillable = [
        'user_id',
        'title',
        'content',
        'date',
        'type',
        'image',
        'published',
        'premium',
    ];

    protected $dates = [
        'date'
    ];

    public function setTypeAttribute($value) {
        $this->attributes['type'] = $value === 'text' ? 0 : 1;
    }

    public function setDateAttribute($value) {
        $this->attributes['date'] = is_null($value) === true ? now() : $value;
    }

    // always when we will set 'title' attribute on Post model this method will run
    public function setTitleAttribute($value) {
        $this->attributes['title'] = $value;
        $this->attributes['slug'] = Str::slug($value);
    }

    // method that will run when we try to read an attribute
    public function getTitleAttribute() {
        return $this->attributes['title'];
    }

    // setting which column laravel will look at when getting data under /posts/{post} route,
    // in this case it will look for posts that will have value of 'slug' column equal to value under {post} placeholder
    public function getRouteKeyName() {
        return 'slug';
    }

    // after creating this method we can get data it returns with $post->excerpt
    public function getExcerptAttribute() {
        return Str::limit(strip_tags($this->content), 300);
    }

    public function getTagsListAttribute() {
//        $tagsString = '';
//
//        $tags = $this->tags()->get();
//
//        foreach($tags as $tag) {
//            $tagsString .= "{$tag->name} ";
//        }
//
//        return $tagsString;
        $tags = $this->tags()->get();

        $tagsString = $tags->implode('name', ' ');

        return $tagsString;
    }

    public function getPhotoAttribute() {
        // we now have two types of images in the db: local images, uploaded on our server by users and
        // images hosted outside of our architecture
        return Str::startsWith($this->image, 'http') === true ? $this->image : Storage::url($this->image);
    }

    // receives query when using this model somewhere in the app, can modify it. In this case: Post::published()->... will
    // only return objects with 'published' field set to 1.
    public function scopePublished($query) {
        $user = auth()->user();

        // checking if user is logged in and if hes an admin
        if (is_null($user) === false && $user->isAdmin() === true) {
            return $query;
        }

        if (is_null($user) === true) {
            $query->where('premium', '<>', 1);
        }

        return $query->where('published', 1);
    }

//    public function user() {
//        return $this->belongsTo(User::class);
//    }
    // this will allow us to find this posts owner, laravel will, by default, search for 'user_id', because the model its
    // related to is called User. If foreign key's name is not this, you need to specify it by:

    public function author() {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }
    // because the method's name is author, laravel will look for author_id column in posts table. It will not find it as we have user_id
    // column instead. Thats when we can specify the foreign key and owner key as shown above

    public function comments() {
        return $this->hasMany(Comment::class);
    }

    public function tags() {
        return $this->belongsToMany(Tag::class);
    }
    // $post->tags()->attach($tagId) will attach a tag to a post later on
    // $post->tags()->get() will retrieve all the tags attached to this post
    // $post->tags()->find($id) will look for tags of specific id attached to this post

    public function toFeedItem() {
        return FeedItem::create([
            'id' => $this->id,
            'title' => $this->title,
            'summary' => $this->excerpt,
            'updated' => $this->updated_at,
            'link' => route('posts.show', $this->slug),
            'author' => $this->author->name,
        ]);
    }

    public static function getFeedItems() {
        return Post::published()->get();
    }
}

resources/views/pages/about.blade.php
@extends('layouts.master')
@section('title', 'About me')

@section('content')

    ABOUT ME

@endsection

resources/views/pages/contact.blade.php
@extends('layouts.master')
@section('title', 'Contact us!')

@section('content')
<div class="wrapper">
    <div class="rte">
        <h1>Contact</h1>
    </div>

    <form method="POST" action="{{ route('contact.send') }}">
        @csrf

        <div class="form-fieldset">
            <input class="form-field {{ $errors->has('email') ? 'is-invalid' : '' }}" type="email" name="email" placeholder="Your e-mail" value="{{ auth()->user()->email }}">
        </div>
        <div class="form-fieldset">
            <input class="form-field {{ $errors->has('subject') ? 'is-invalid' : '' }}" type="text" name="subject" placeholder="Tell us we will be talking about">
        </div>
        <div class="form-fieldset is-wide">
            <textarea class="form-textarea {{ $errors->has('message') ? 'is-invalid' : '' }}" name="message" placeholder="Tell us exactly what the problem is."></textarea>
        </div>
        <button class="button">Send</button>
    </form>
</div>
@endsection

resources/views/pages/post.blade.php
@extends('layouts.master')
@section('title', $post->title)

@section('content')
    @if ($post->type === 0)
        <article class="post formatText">
            <div class="postContent">
                <div class="wrapper">
                    @if ($post->premium)
                        <i class="postPremium fa fa-star"></i>
                    @endif
                    <h2 class="postTitle">
                        <a href="{{ route('posts.show', $post->slug) }}">{{ $post->title }}</a>
                    </h2>
                    <div class="rte">
                        {!! $post->content !!}
                    </div>
                </div>
            </div>
            <div class="meta">
                @if($post->tags->count() > 0)
                    <ul class="tags">
                        <li><i class="fa fa-tags"></i></li>
                        @foreach($post->tags as $tag)
                            <li>{{ $tag->name }}</li><li>
                                <a href="{{ route('tag.show', $tag->slug) }}">{{ $tag->name }}</a>
                            </li>
                        @endforeach
                    </ul>
                @endif
                <div class="flex flex-sb">
                    <p class="date"><i class="fa fa-clock-o"></i>{{ $post->date->diffForHumans() }} <i class="fa fa-user"></i> by {{ $post->author->name }}</p>
                    @can('manage-posts')
                    <p>
                        <a href="{{ route('admin.post.edit', $post->id) }}" class="link"><i class="fa fa-edit"></i> Edytuj</a>
                    </p>
                    @endcan
                </div>
            </div>
        </article>
    @elseif ($post->type === 1)
        <article class="post formatPhoto">
            <figure class="postImage">
                @if ($post->premium)
                    <i class="postPremium fa fa-star"></i>
                @endif
                <a href="#">
                    <img src="{{ $post->photo }}" alt="" class="mainPhoto">
                </a>
                <div class="cover"
                     style="background: url({{ $post->photo }}) no-repeat;">
                </div>
            </figure>
            <div class="meta">
                @if($post->tags->count() > 0)
                    <ul class="tags">
                        <li><i class="fa fa-tags"></i></li>
                        @foreach($post->tags as $tag)
                            <li>
                                <a href="{{ route('tag.show', $tag->slug) }}">{{ $tag->name }}</a>
                            </li>
                        @endforeach
                    </ul>
                @endif
                <div class="flex flex-sb">
                    <p class="date"><i class="fa fa-clock-o"></i>{{ $post->date->diffForHumans() }}<i class="fa fa-user"></i> by {{ $post->author->name }}</p>
                    @can('manage-posts')
                    <p>
                        <a href="{{ route('admin.post.edit', $post->id) }}" class="link"><i class="fa fa-edit"></i> Edytuj</a>
                    </p>
                    @endcan
                </div>
            </div>
        </article>
    @endif
    <section class="comments">
        <div class="wrapper">
            <div class="rte">
                <h2>{{ count($post->comments) }} comments</h2>
            </div>
            <div class="comments-list">
            @foreach ($post->comments as $comment)
                <article class="comment">
                    <div class="comment-meta">
                        <img src="{{ \Thomaswelton\LaravelGravatar\Facades\Gravatar::src($comment->author->email, 100) }}" alt="Mark Joel" class="comment-avatar">
                        <span class="comment-user">{{ $comment->author->name }}</span>
                        <span class="comment-date">{{ $comment->date->format('d.m.Y') }}</span>
                    </div>
                    <p class="comment-body rte">{{ $comment->content }}</p>
                </article>
            @endforeach
            </div>
            <div class="comments-add">
                <div class="rte">
                    <h2>Add comment</h2>
                </div>
                <form method="POST" action="{{ route('comment.create') }}">
                    @csrf
                    <input type="hidden" name="post_id" value="{{ $post->id }}">

                    <div class="form-fieldset is-full">
                        <textarea name="content" class="form-textarea {{ $errors->has('content') ? 'is-invalid' : '' }}" placeholder="Your comment">{{ old('content') }}</textarea>
                    </div>
                    <button class="button">Submit</button>
                </form>
            </div>
        </div>
    </section>
@endsection

resources/views/pages/posts.blade.php
@extends('layouts.master')
@section('title', 'Posts')

@section('content')
@if (count($posts) === 0)
    <div class="container">
        <p>No posts available</p>
    </div>
@else
    @foreach($posts as $post)
        @if ($post->type === 0)
            <article class="post formatText">
                <div class="postContent">
                    <div class="wrapper">
                        @if ($post->premium)
                            <i class="postPremium fa fa-star"></i>
                        @endif
                        <h2 class="postTitle">
                            <a href="{{ route('posts.show', $post->slug) }}">{{ $post->title }}</a>
                        </h2>
                        <div class="rte">
                            {!! $post->excerpt !!}
                            <p class="readMore">
                                <a href="{{ route('posts.show', $post->slug) }}">Keep reading</a>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="meta">
                    @if($post->tags->count() > 0)
                        <ul class="tags">
                            <li><i class="fa fa-tags"></i></li>
                            @foreach($post->tags as $tag)
                                <li>
                                    <a href="{{ route('tag.show', $tag->slug) }}">{{ $tag->name }}</a>
                                </li>
                            @endforeach
                        </ul>
                    @endif
                    <div class="flex flex-sb">
                        <p class="date"><i class="fa fa-clock-o"></i>{{ $post->date->diffForHumans() }} <i class="fa fa-user"></i> by {{ $post->author->name }}</p>
                        @can('manage-posts')
                        <p>
                            <a href="{{ route('admin.post.edit', $post->id) }}" class="link"><i class="fa fa-edit"></i> Edytuj</a>
                        </p>
                        @endcan
                    </div>
                </div>
            </article>
        @elseif ($post->type === 1)
            <article class="post formatPhoto">
                <figure class="postImage">
                    @if ($post->premium)
                        <i class="postPremium fa fa-star"></i>
                    @endif
                    <a href="{{ route('posts.show', $post->slug) }}">
                        <img src="{{ $post->photo }}" alt="" class="mainPhoto">
                    </a>
                    <div class="cover"
                         style="background: url({{ $post->photo }}) no-repeat;">
                    </div>
                </figure>
                <div class="meta">
                    @if($post->tags->count() > 0)
                    <ul class="tags">
                        <li><i class="fa fa-tags"></i></li>
                        @foreach($post->tags as $tag)
                            <li>
                                <a href="{{ route('tag.show', $tag->slug) }}">{{ $tag->name }}</a>
                            </li>
                        @endforeach
                    </ul>
                    @endif
                    <div class="flex flex-sb">
                        <p class="date"><i class="fa fa-clock-o"></i>{{ $post->date->diffForHumans() }} <i class="fa fa-user"></i> by {{ $post->author->name }}</p>
                        @can('manage-posts')
                        <p>
                            <a href="{{ route('admin.post.edit', $post->id) }}" class="link"><i class="fa fa-edit"></i> Edytuj</a>
                        </p>
                        @endcan
                    </div>
                </div>
            </article>
        @endif
    @endforeach

    @include ('partials.pagination', ['pagination' => $posts])
@endif
@endsection